- name: Build APK
  run: |
    chmod +x android/gradlew
    android/gradlew -p android app:assembleRelease --stacktrace
    mkdir -p build/app/outputs/flutter-apk
    APK=$(find android/app/build/outputs -type f -name "*.apk" | head -n 1)
    cp "$APK" build/app/outputs/flutter-apk/app-release.apk
    ls -lh build/app/outputs/flutter-apk/app-release.apk
